import os
import json
import logging
import re
import requests

logger = logging.getLogger(__name__)

_NVAI_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
_MODEL    = "meta/llama-3.1-8b-instruct"

def _get_headers() -> dict:
    api_key = os.getenv("NVIDIA_API_KEY")
    if not api_key:
        raise EnvironmentError("NVIDIA_API_KEY is not set. Check backend/.env")
    return {
        "Authorization": f"Bearer {api_key}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }

SYSTEM_PROMPT = """
You are an expert ATS (Applicant Tracking System) Analyzer and Technical Recruiter.
Your goal is to evaluate the provided resume text (extracted from a PDF) for ATS readability, impact, formatting, and content quality.

Analyze the resume and output ONLY a raw JSON object containing the following structure:
{
  "score": <integer from 0 to 100>,
  "issues": [
    {
      "severity": "critical" | "warning",
      "message": "<Description of the issue>"
    }
  ],
  "tips": [
    "<Actionable advice to improve the resume>"
  ]
}

EVALUATION CRITERIA (BE RUTHLESS BUT ACCURATE):
1. ATS Parsability: If the text looks completely jumbled or has weird characters instead of bullet points, penalize it.
2. Contact Info: Carefully scan the first section for an Email and Phone number. Note that they might be separated by symbols like `|` or `•`. If either is truly missing, flag it as a CRITICAL issue. Do NOT complain about standard email formats.
3. Work Experience Structure: Must clearly show Company, Job Title, Dates, and bullet points. If dates are missing or inconsistent, flag it as a warning.
4. Action Verbs & Impact: Bullet points starting with "Responsible for" or "Worked on" instead of strong action verbs (e.g., "Spearheaded", "Developed") should be flagged as warnings. Recommend adding quantifiable metrics (numbers, %, $) if missing.
5. Missing Sections: If standard sections (Experience, Education, Skills) are missing or named creatively (e.g., "What I've done"), flag it.

CONSTRAINTS & SCORING:
- Be 100% honest but do not hallucinate missing information. Double-check for phone numbers (often formatted with country codes like +91, +1, etc.) and emails before marking them missing.
- A truly average resume should score between 60-75. Only exceptional, flawlessly formatted resumes with metrics should score above 85.
- ALWAYS find at least 1-2 minor "warning" issues or constructive tips.
- Do NOT output any markdown blocks like ```json.
- Output ONLY the raw JSON string starting with { and ending with }.
"""

def _strip_fences(raw: str) -> str:
    """Strip markdown code fences if the model wrapped its JSON output."""
    raw = raw.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    return raw.strip()

def analyze_ats_compliance(resume_text: str, force_verified: bool = False, timeout: int = 180) -> dict:
    """
    Analyzes the resume text and returns a structured ATS evaluation using the NIM API.
    """
    logger.info(f"Analyzing resume for ATS compliance (force_verified={force_verified})...")
    
    try:
        headers = _get_headers()
        
        payload = {
            "model": _MODEL,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Here is the parsed resume text to evaluate:\n\n{resume_text}"}
            ],
            "max_tokens": 1000,
            "temperature": 0.2,
            "stream": False
        }
        
        response = requests.post(_NVAI_URL, headers=headers, json=payload, timeout=timeout)
        
        if not response.ok:
            logger.error(f"NIM API error: {response.status_code} - {response.text}")
            raise RuntimeError(f"NIM API call failed with status {response.status_code}")
            
        data = response.json()
        raw_text = data["choices"][0]["message"]["content"]
        raw_text = _strip_fences(raw_text)
        
        result = json.loads(raw_text)
        
        # Validate structure
        if "score" not in result or "issues" not in result or "tips" not in result:
            raise ValueError("LLM response missing required keys")
            
        if force_verified:
            # The resume is generated by our system, boost the score
            # and remove any critical formatting/ATS unreadable errors
            result["score"] = max(95, result["score"])
            # Remove any critical issues, downgrade them to warnings or remove them
            filtered_issues = []
            for issue in result["issues"]:
                if issue.get("severity") == "critical":
                    # Downgrade it
                    issue["severity"] = "warning"
                filtered_issues.append(issue)
                
            result["issues"] = filtered_issues
            # Add a tip about our platform
            result["tips"].insert(0, "Great job using MyCareerCV! Your format is fully ATS-compliant.")
            
        return result
        
    except Exception as e:
        logger.error(f"ATS analysis failed: {e}")
        # Fallback response in case of LLM failure
        return {
            "score": 95 if force_verified else 75,
            "issues": [
                {"severity": "warning", "message": "Could not complete deep AI analysis. Ensure standard ATS fonts and formatting are used."}
            ],
            "tips": [
                "Always use standard section headers (Experience, Education, Skills).",
                "Ensure your contact information is easy to find at the top."
            ]
        }
