// Default customMeta payloads for every element type the toolbox can create.
// These are merged over Fabric's native serialization during save/load.

export const META_DEFAULTS = {
  text: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'field',
    isPlaceholder: false,
    repeatable: false,
    sectionKey: null,
    maxLines: null,
    overflowBehavior: 'truncate',
    listSeparator: ', ',
    bulletStyle: '•',
    bulletSpacing: 4,
    dateFormat: null,
    locked: false,
    friendlyLabel: 'Text',
  },
  richText: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'field',
    isPlaceholder: false,
    repeatable: false,
    sectionKey: null,
    maxLines: null,
    overflowBehavior: 'expand',
    listSeparator: '\n',
    bulletStyle: '•',
    bulletSpacing: 6,
    dateFormat: null,
    locked: false,
    friendlyLabel: 'Rich Text Block',
  },
  bulletList: {
    dataPath: null,
    bindingType: 'list',
    templateRole: 'field',
    isPlaceholder: false,
    repeatable: false,
    sectionKey: null,
    maxLines: null,
    overflowBehavior: 'expand',
    listSeparator: '\n',
    bulletStyle: '•',
    bulletSpacing: 6,
    dateFormat: null,
    locked: false,
    friendlyLabel: 'Bullet List',
  },
  rect: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'decoration',
    isPlaceholder: false,
    repeatable: false,
    sectionKey: null,
    maxLines: null,
    overflowBehavior: 'none',
    locked: false,
    friendlyLabel: 'Rectangle',
  },
  circle: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'decoration',
    isPlaceholder: false,
    repeatable: false,
    sectionKey: null,
    locked: false,
    friendlyLabel: 'Circle',
  },
  line: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'decoration',
    isPlaceholder: false,
    locked: false,
    friendlyLabel: 'Line',
  },
  divider: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'decoration',
    isPlaceholder: false,
    locked: false,
    friendlyLabel: 'Divider',
  },
  imagePlaceholder: {
    dataPath: null,
    bindingType: 'image',
    templateRole: 'placeholder',
    isPlaceholder: true,
    locked: false,
    friendlyLabel: 'Image Placeholder',
  },
  photoFrame: {
    dataPath: 'photo',
    bindingType: 'image',
    templateRole: 'placeholder',
    isPlaceholder: true,
    locked: false,
    friendlyLabel: 'Photo Frame',
  },
  repeatableGroup: {
    dataPath: null,
    bindingType: 'none',
    templateRole: 'section',
    isPlaceholder: false,
    repeatable: true,
    sectionKey: null,
    childBindings: {},
    locked: false,
    friendlyLabel: 'Repeatable Section',
  },
};

// Known bindable data paths from the resume schema
export const SCHEMA_PATHS = {
  scalars: [
    { path: 'full_name',         label: 'Full Name' },
    { path: 'headline',          label: 'Headline' },
    { path: 'summary',           label: 'Summary' },
    { path: 'contact.email',     label: 'Email' },
    { path: 'contact.phone',     label: 'Phone' },
    { path: 'contact.location',  label: 'Location' },
    { path: 'contact.linkedin',  label: 'LinkedIn' },
    { path: 'contact.github',    label: 'GitHub' },
    { path: 'contact.portfolio', label: 'Portfolio' },
  ],
  lists: [
    { path: 'skills.technical',  label: 'Technical Skills' },
    { path: 'skills.soft',       label: 'Soft Skills' },
    { path: 'skills.languages',  label: 'Languages' },
    { path: 'skills.other',      label: 'Other Skills' },
  ],
  sections: [
    { key: 'work_experience',  label: 'Work Experience',  fields: ['company','title','location','start_date','end_date','responsibilities'] },
    { key: 'education',        label: 'Education',        fields: ['institution','degree','field_of_study','graduation_year','gpa','honors'] },
    { key: 'certifications',   label: 'Certifications',   fields: ['name','issuer','date','credential_id','url'] },
    { key: 'awards',           label: 'Awards',           fields: ['title','issuer','date','description'] },
    { key: 'publications',     label: 'Publications',     fields: ['title','publisher','date','url'] },
    { key: 'volunteer',        label: 'Volunteer',        fields: ['organisation','role','start_date','end_date','description'] },
    { key: 'projects',         label: 'Projects',         fields: ['name','description','technologies','url','date'] },
  ],
};
